//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Skis
    {

        
        public int Id { get; set; }


        [StringLength(30, MinimumLength = 2, ErrorMessage = "Name must be between 2 and 30 characters")]
        [Required(ErrorMessage = "Required field")]
        public string Sk_Name { get; set; }
      

        [Range(30,300, ErrorMessage ="Length must be between 30 and 300 cm")]
        [Required(ErrorMessage ="Required field") ]
        public Nullable<int> Sk_Length { get; set; }


        [Range(30, 300, ErrorMessage = "Width must be between 30 and 300 mm")]
        [Required(ErrorMessage = "Required field")]
        public Nullable<int> Sk_Width { get; set; }

       
        public int Sk_Origin { get; set; }
    


        public virtual Brand Brand { get; set; }

      
    }
}
